### ISSUE TITLE
Fill out readme.md with project information and use case examples

### ISSUE THREAD

**Issue by TheoBr** [DeepRemix/DeepRemix#6]
At this moment, it is unclear what this project does, not to mention how to use it. I would love a project description and some basic use examples so I can follow along as development progresses

**Comment by hodgka** [comment]
Better? We'll update more when we have more stuff in place.

#7

**Comment by TheoBr** [comment]
Much better! Would love to know what kinds of "song" data types you take though. Midi, MP3?

**Comment by hodgka** [comment]
We're taking in WAV files. It'll get updated eventually
